
DROP TABLE IF EXISTS `user`;

-- create new table
CREATE TABLE `user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name`varchar(45) DEFAULT NULL,
  `email` varchar(45) DEFAULT NULL,
  `password` varchar(100) DEFAULT NULL,
  `age` varchar(45) DEFAULT NULL,
  `location` varchar(45) DEFAULT NULL,
  `bio` varchar(45) DEFAULT NULL,
  `phone_number` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


CREATE TABLE `role` (
  `id` int NOT NULL AUTO_INCREMENT,
  `role_name`varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


CREATE TABLE `user_role` (
	`user_id` int NOT NULL,
	`role_id` int NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;





----------------

-- task 1
SELECT INV_NUMBER, INV_DATE, CUS_FNAME, CUS_LNAME FROM INVOICE a, customer b WHERE a.CUS_CODE = b.CUS_CODE;

-- task 4
SELECT I.INV_DATE, P.P_CODE, P.P_DESCRIPT FROM INVOICE I INNER JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER JOIN PRODUCT P ON L.P_CODE = P.P_CODE WHERE I.INV_NUMBER = 1008;

-- task 2
SELECT V.V_CODE, V.V_NAME, COUNT(P.P_CODE) AS NUM_PRODS, AVG(P.P_PRICE) AS AVG_PROD_PRICE FROM VENDOR V JOIN PRODUCT P ON V.V_CODE = P.V_CODE GROUP BY V.V_CODE, V.V_NAME;

-- task 6
SELECT P_CODE, P_DESCRIPT FROM PRODUCT WHERE P_INDATE BETWEEN '2018-02-01' AND '2018-02-30';

-- task 3
SELECT P.P_CODE, P.P_DESCRIPT, V.V_CODE, V.V_NAME FROM PRODUCT P LEFT JOIN vendor V ON P.V_CODE = V.V_CODE;

-- task 5
SELECT CONCAT(E.EMP_FNAME, ' ', E.EMP_LNAME) AS Employee, CONCAT(M.EMP_FNAME, ' ', M.EMP_LNAME) AS Manager FROM EMP E, EMP M WHERE E.EMP_MGR = M.EMP_NUM;

ALTER TABLE EMPLOYEE RENAME COLUMN EMP_MGR TO EMP_MGR_NUM;
